name: chord_transposer
description: A Dart package for transposing chords into any given key.
version: 0.0.2
homepage: https://github.com/JakesMD/chord_transposer

environment:
  sdk: '>=3.7.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
